### PR TITLE
Fix contributors to new version

### PR DESCRIPTION
**Pull request by chikathreesix**
Previous contributors endpoint is now deprecated so I fixed it to the new version, which is now separated into 2 endpoints.

Previous
/contributors/user_id.json (GET, PUT)

New
/contributors/user_id/count.json (GET)
/contributors/user_id/meta.json (GET, PUT)

### CODE REVIEW

**Comment by fadhlirahim** [comment]
@chikathreesix can you add `how to use` in the README documentation?

**Comment by chikathreesix** [comment]
Oh sure, sorry

**Comment by fadhlirahim** [comment]
hey, no need to apologize :smile:

**Comment by chikathreesix** [comment]
Here is the document

**Comment by fadhlirahim** [comment]
cool. :+1:

**Comment by fadhlirahim** [comment]
Merged. Had to merge using command line. Will close this pull request.

**Pull request closed without merging**
